// Code generated by "stringer -type=PacketCode"; DO NOT EDIT

package radius

import "fmt"

const (
	_PacketCode_name_0 = "AccessRequestAccessAcceptAccessRejectAccountingRequestAccountingResponse"
	_PacketCode_name_1 = "AccessChallengeStatusServerStatusClient"
	_PacketCode_name_2 = "Reserved"
)

var (
	_PacketCode_index_0 = [...]uint8{0, 13, 25, 37, 54, 72}
	_PacketCode_index_1 = [...]uint8{0, 15, 27, 39}
	_PacketCode_index_2 = [...]uint8{0, 8}
)

func (i PacketCode) String() string {
	switch {
	case 1 <= i && i <= 5:
		i -= 1
		return _PacketCode_name_0[_PacketCode_index_0[i]:_PacketCode_index_0[i+1]]
	case 11 <= i && i <= 13:
		i -= 11
		return _PacketCode_name_1[_PacketCode_index_1[i]:_PacketCode_index_1[i+1]]
	case i == 255:
		return _PacketCode_name_2
	default:
		return fmt.Sprintf("PacketCode(%d)", i)
	}
}
