package storage

//generated by embd
const archiveSession = "INSERT INTO session_log (\n  assigned_ip,\n  bytes_in,\n  bytes_out,\n  client_ip,\n  nas_ip,\n  packets_in,\n  packets_out,\n  session_id,\n  session_time,\n  user,\n  time_added\n  )\nSELECT\n  assigned_ip,\n  bytes_in,\n  bytes_out,\n  client_ip,\n  nas_ip,\n  packets_in,\n  packets_out,\n  session_id,\n  session_time,\n  user,\n  time_added\nFROM session\nWHERE user = ?\n  AND session_id = ?\n  AND nas_ip = ?"
