package storage

//generated by embd
const insertSession = "INSERT INTO\tsession (\n  session_id,\n  user,\n  time_added,\n  nas_ip,\n  assigned_ip,\n  client_ip,\n  bytes_in,\n  bytes_out,\n  packets_in,\n  packets_out,\n  session_time\n ) VALUES (?, ?, ?, ?, ?, ?, 0, 0, 0, 0, 0)"
