package storage

//generated by embd
const insertAcct = "INSERT INTO accounting (\n    user,\n    date,\n    bytes_in,\n    bytes_out,\n    packets_in,\n    packets_out,\n    hostname\n) VALUES (?, ?, ?, ?, ?, ?, ?)"
