package storage

//generated by embd
const selectUser = "SELECT pass,\n       block_remaining,\n       active_until,\n       1,\n       simultaneous_use,\n       dedicated_ip,\n       CONCAT(ratelimit_up, ratelimit_unit, '/', ratelimit_down, ratelimit_unit),\n       dns.one, dns.two\nFROM      user\nJOIN      product ON user.product_id = product.id\nLEFT JOIN dns     ON user.dns_id     = dns.id\nWHERE user = ?\n"
