package storage

//generated by embd
const updateSession = "UPDATE session SET\n  bytes_in     = bytes_in + ?,\n  bytes_out    = bytes_out + ?,\n  packets_in   = packets_in + ?,\n  packets_out  = packets_out + ?,\n  session_time = ?\nWHERE user = ?\n  AND session_id = ?\n  AND nas_ip = ?"
